alias ali='nvim ~/.config/zsh/aliases.zsh'
alias emsnip='nvim ~/.config/nvim/snippets_custom.json'
alias re='source ~/.config/zsh/.zshrc'
alias vim='nvim'
alias nvim='~/./bin/nvim.appimage'
alias vimplug='nvim ~/.config/nvim/plugins.vim'
alias vimrc='nvim ~/.config/nvim/init.vim'
alias zshenv='nvim ~/.zshenv'
alias zshrc='nvim ~/.config/zsh/.zshrc'

# Devops
alias d='docker'
alias dc='docker container'
alias dcm='docker compose'
alias dcbuild='docker compose up --build -d'
alias dclog='docker compose logs --tail 20 -f'
alias mvn='bin/apache-maven-3.9.2/bin/mvn'
alias vpn='sudo openvpn --config ~/vpn.ovpn'

# Git
alias ga='git add'
alias gb='git branch -a'
alias gc='git commit -m'
alias gcl='git clone'
alias gl='git log --oneline'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gpl='git pull origin'
alias gpld='git pull origin develop'
alias gplm='git pull origin main'
alias gplmt='git pull origin master'
alias gps='git push origin'
alias gpsd='git push origin develop'
alias gpsm='git push origin main'
alias grd='cd "$(git rev-parse --show-toplevel)"'
alias gs='git status'
alias gst='git stash -u'
alias gstl='git stash list'
alias gstp='git stash pop'

# Navigation
alias b='cd ..'
alias cl='clear'
alias initnodejs='rsync -av --exclude={".git","README.md","node_modules","yarn.lock","dist"} ~/Projects/personal/portfolio/nodejs-project-template/* .'
alias pr='cd ~/Projects'
alias prp='cd ~/Projects/personal'
alias prp2='cd ~/Projects/personal-2'
alias prw='cd ~/Projects/work'

# Program
alias budget='z actual && yarn start'
alias goland='~/./bin/GoLand-2023.2/bin/goland.sh'
alias phpstorm='~/./bin/PhpStorm-232.8660.205/bin/phpstorm.sh'
alias cpf='xclip -sel c <'
alias envi='doppler setup && doppler run -- air'
alias ex='exa --icons --color=always --group-directories-first -a'
alias exl='exa --icons --color=always --group-directories-first -a -l'
alias ext='exa --icons --color=always --group-directories-first --ignore-glob=".git|node_modules" -a -T'
alias o='code .'
alias rip='rip -i --graveyard ~/.local/share/Trash'
alias xmpvm='sudo ~/./xampp.sh'
alias xmp='sudo /opt/lampp/lampp'
